"""Add resume parsing fields

Revision ID: e04ef29c520a
Revises: cae7bbeff042
Create Date: 2025-10-23 11:40:30.004597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e04ef29c520a'
down_revision = 'cae7bbeff042'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('file_name', sa.String(length=255), nullable=True))
    op.add_column('resumes', sa.Column('file_size', sa.String(length=50), nullable=True))
    op.add_column('resumes', sa.Column('file_type', sa.String(length=100), nullable=True))
    op.add_column('resumes', sa.Column('parse_status', sa.String(length=50), nullable=True))
    op.add_column('resumes', sa.Column('parse_error', sa.JSON(), nullable=True))
    op.add_column('resumes', sa.Column('is_default', sa.Boolean(), nullable=True))
    op.add_column('resumes', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('resumes', sa.Column('parsed_at', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'parsed_at')
    op.drop_column('resumes', 'is_deleted')
    op.drop_column('resumes', 'is_default')
    op.drop_column('resumes', 'parse_error')
    op.drop_column('resumes', 'parse_status')
    op.drop_column('resumes', 'file_type')
    op.drop_column('resumes', 'file_size')
    op.drop_column('resumes', 'file_name')
    # ### end Alembic commands ###
