"""enhance_cover_letter_model_for_ai_generation

Revision ID: 0d287936cc84
Revises: 6e6f6227bb9d
Create Date: 2025-10-23 23:06:01.070555

"""
from alembic import op
import sqlalchemy as sa
from app.db.types import GUID


# revision identifiers, used by Alembic.
revision = '0d287936cc84'
down_revision = '6e6f6227bb9d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cover_letters', sa.Column('job_title', sa.String(length=255), nullable=True))
    op.add_column('cover_letters', sa.Column('company_name', sa.String(length=255), nullable=True))
    op.add_column('cover_letters', sa.Column('job_description', sa.Text(), nullable=True))
    op.add_column('cover_letters', sa.Column('intro_paragraph', sa.Text(), nullable=True))
    op.add_column('cover_letters', sa.Column('body_paragraphs', sa.JSON(), nullable=True))
    op.add_column('cover_letters', sa.Column('closing_paragraph', sa.Text(), nullable=True))
    op.add_column('cover_letters', sa.Column('emphasized_skills', sa.JSON(), nullable=True))
    op.add_column('cover_letters', sa.Column('custom_intro', sa.Text(), nullable=True))
    op.add_column('cover_letters', sa.Column('company_research', sa.Text(), nullable=True))
    op.add_column('cover_letters', sa.Column('referral_name', sa.String(length=255), nullable=True))
    op.add_column('cover_letters', sa.Column('address_gap', sa.Text(), nullable=True))
    op.add_column('cover_letters', sa.Column('career_change_context', sa.Text(), nullable=True))
    op.add_column('cover_letters', sa.Column('strict_factual', sa.Boolean(), nullable=True))
    op.add_column('cover_letters', sa.Column('token_usage', sa.String(length=50), nullable=True))
    op.add_column('cover_letters', sa.Column('cost', sa.String(length=50), nullable=True))
    op.add_column('cover_letters', sa.Column('quality_score', sa.Float(), nullable=True))
    op.add_column('cover_letters', sa.Column('status', sa.String(length=50), nullable=True))
    op.add_column('cover_letters', sa.Column('version_number', sa.Integer(), nullable=True))
    op.add_column('cover_letters', sa.Column('parent_id', GUID(), nullable=True))
    op.add_column('cover_letters', sa.Column('variation_number', sa.Integer(), nullable=True))
    op.add_column('cover_letters', sa.Column('user_rating', sa.Integer(), nullable=True))
    op.add_column('cover_letters', sa.Column('resulted_in_interview', sa.Boolean(), nullable=True))
    op.add_column('cover_letters', sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    # Note: SQLite doesn't support adding foreign keys after table creation
    # The parent_id relationship is defined in the model
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cover_letters', type_='foreignkey')
    op.drop_column('cover_letters', 'updated_at')
    op.drop_column('cover_letters', 'resulted_in_interview')
    op.drop_column('cover_letters', 'user_rating')
    op.drop_column('cover_letters', 'variation_number')
    op.drop_column('cover_letters', 'parent_id')
    op.drop_column('cover_letters', 'version_number')
    op.drop_column('cover_letters', 'status')
    op.drop_column('cover_letters', 'quality_score')
    op.drop_column('cover_letters', 'cost')
    op.drop_column('cover_letters', 'token_usage')
    op.drop_column('cover_letters', 'strict_factual')
    op.drop_column('cover_letters', 'career_change_context')
    op.drop_column('cover_letters', 'address_gap')
    op.drop_column('cover_letters', 'referral_name')
    op.drop_column('cover_letters', 'company_research')
    op.drop_column('cover_letters', 'custom_intro')
    op.drop_column('cover_letters', 'emphasized_skills')
    op.drop_column('cover_letters', 'closing_paragraph')
    op.drop_column('cover_letters', 'body_paragraphs')
    op.drop_column('cover_letters', 'intro_paragraph')
    op.drop_column('cover_letters', 'job_description')
    op.drop_column('cover_letters', 'company_name')
    op.drop_column('cover_letters', 'job_title')
    # ### end Alembic commands ###
