"""add_ai_generation_fields_to_resume_versions

Revision ID: 6e6f6227bb9d
Revises: e04ef29c520a
Create Date: 2025-10-23 22:57:18.051573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e6f6227bb9d'
down_revision = 'e04ef29c520a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume_versions', sa.Column('length', sa.String(length=50), nullable=True))
    op.add_column('resume_versions', sa.Column('style', sa.String(length=50), nullable=True))
    op.add_column('resume_versions', sa.Column('target_company', sa.String(length=255), nullable=True))
    op.add_column('resume_versions', sa.Column('keywords', sa.JSON(), nullable=True))
    op.add_column('resume_versions', sa.Column('strict_factual', sa.Boolean(), nullable=True))
    op.add_column('resume_versions', sa.Column('token_usage', sa.String(length=50), nullable=True))
    op.add_column('resume_versions', sa.Column('cost', sa.String(length=50), nullable=True))
    op.add_column('resume_versions', sa.Column('status', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resume_versions', 'status')
    op.drop_column('resume_versions', 'cost')
    op.drop_column('resume_versions', 'token_usage')
    op.drop_column('resume_versions', 'strict_factual')
    op.drop_column('resume_versions', 'keywords')
    op.drop_column('resume_versions', 'target_company')
    op.drop_column('resume_versions', 'style')
    op.drop_column('resume_versions', 'length')
    # ### end Alembic commands ###
